# vi: ft=yaml
#
import = [
	"~/lib/dotfiles/alacritty/catppuccin.yml",
]
live_config_reload = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[colors.cursor]
cursor = "#eeeeee"

[colors.primary]
background = "#222222"

[window]
opacity = 0.97
dynamic_title = true
dynamic_padding = true
decorations = "none"

  [window.padding]
  x = 5
  y = 5

  [window.dimensions]
  columns = 120
  lines = 30

[scrolling]
history = 10_000
multiplier = 3

[bell]
duration = 100
color = "#22212C"

  # [bell.command]
  # program = "afplay"
  # args = [ "/System/Library/Sounds/Tink.aiff" ]

[font]
size = 12

  [font.normal]
  family = "MesloLGS NF"

  [font.bold]
  family = "MesloLGS NF"

  [font.italic]
  family = "MesloLGS NF"

  [font.bold_italic]
  family = "MesloLGS NF"

[cursor.style]
shape = "Beam"
blinking = "On"

# key_bindings:
#   - { key: N,        mods: Command, action: CreateNewWindow }
#   - { key: E,        mods: Alt,     chars: "\x1be"          }
#   - { key: Y,        mods: Alt,     chars: "\x1by"          }
#   - { key: F,        mods: Alt,     chars: "\x1bf"          }
#   - { key: B,        mods: Alt,     chars: "\x1bb"          }
#   - { key: L,        mods: Alt,     chars: "\x1bl"          }
#   - { key: O,        mods: Alt,     chars: "\x1bo"          }
#   - { key: W,        mods: Alt,     chars: "\x1bw"          }
#   - { key: D,        mods: Alt,     chars: "\x1bd"          }
#   - { key: S,        mods: Alt,     chars: "\x1bs"          }
#   - { key: H,        mods: Alt,     chars: "\x1bh"          }
#   - { key: P,        mods: Alt,     chars: "\x1bp"          }
#   - { key: V,        mods: Alt,     chars: "\x1bv"          }
#   - { key: T,        mods: Alt,     chars: "\x1bt"          }
#   - { key: U,        mods: Alt,     chars: "\x1bu"          }
#   - { key: C,        mods: Alt,     chars: "\x1bc"          }

# mouse_bindings:
#   - { mouse: Middle, action: PasteSelection }
