#!/usr/local/bin/zsh
# This hook is sourced after a new virtualenv is activated.

proj_name=$(basename ${VIRTUAL_ENV})
mkdir -p ${HOME}/code/${proj_name}
add2virtualenv ${HOME}/code/${proj_name}
cd ${HOME}/code/${proj_name}
