#!/usr/bin/zsh
# This hook is run after every virtualenv is activated.

if [ -d $VIRTUAL_ENV ]; then
    # If we aren’t already within the project dir, cd into it
    if [[ ! `pwd` == "$VIRTUAL_ENV*" ]]; then
        export PRE_VENV_ACTIVATE_DIR=`pwd`
        cd "$VIRTUAL_ENV"
    fi
fi

